name: Check

on:
  workflow_call:
    inputs:
      repository:
        type: string
        default: ${{ github.repository }}
      ref:
        type: string
        default: ${{ github.sha }}

      # Internal vars
      coverage-dir:
        type: string
        default: ./coverage
      coverage-lcov:
        type: string
        default: coverage.lcov.info
      coverage-artifact:
        type: string
        default: test-coverage-report

    outputs:
      coverage-artifact: # artifact name
        value: ${{ inputs.coverage-artifact }}
      coverage-lcov: # file name in artifact
        value: ${{ inputs.coverage-lcov }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/make.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      target: build

  lint:
    name: Lint
    uses: ./.github/workflows/make.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      target: lint

  test:
    name: Test
    uses: ./.github/workflows/make.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      name: test
      target: coverage
      args: COVERAGE_DIR=${{ inputs.coverage-dir }} COVERAGE_LCOV=${{ inputs.coverage-dir }}/${{ inputs.coverage-lcov }}
      artifact-name: ${{ inputs.coverage-artifact }}
      artifact-path: ${{ inputs.coverage-dir }}
