name: Check

on:
  push:
  workflow_call:
    outputs:
      coverage_total:
        value: ${{ jobs.check.outputs.coverage_total }}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      coverage_total: ${{ steps.coverage.outputs.total }}
    steps:
      - id: coverage
        run: echo "total=69.69" >> "$GITHUB_OUTPUT"
