name: Check

on:
  push:
  pull_request:

permissions:
#   security-events: write
#   actions: read
  contents: write
  pull-requests: write

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: go test -v ./...

      - name: Coverage Report
        uses: gwatts/go-coverage-action@v1
