name: Check

on:
  workflow_call:
    inputs:
      fetch-url:
        type: string
        default: ${{ github.repositoryUrl }}
      fetch-sha:
        type: string
        default: ${{ github.sha }}

      # Internal vars
      coverage-dir:
        type: string
        default: ./coverage
      coverage-out:
        type: string
        default: coverage.out
      coverage-html:
        type: string
        default: coverage.html

    outputs:
      coverage_total:
        value: ${{ jobs.check.outputs.coverage_total }}

      coverage-out:
        value: ${{ inputs.coverage-out }}
      coverage-html:
        value: ${{ inputs.coverage-html }}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      coverage_total: ${{ steps.coverage.outputs.total }}
    steps:
      - name: Fetch and checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.fetch-url }}
          ref: ${{ inputs.fetch-sha }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Coverage
        id: coverage
        if: ${{ github.event_name }} == pull_request
        shell: bash
        env:
          COVERAGE_OUT: ${{ inputs.coverage-dir }}/${{ inputs.coverage-out }}
          COVERAGE_HTML: ${{ inputs.coverage-dir }}/${{ inputs.coverage-html }}
        run: |
          mkdir -p '${{ inputs.coverage-dir }}'

          go test -coverprofile="$COVERAGE_OUT" ./...
          go tool cover -html="$COVERAGE_OUT" -o="$COVERAGE_HTML"

          TOTAL="$(go tool cover -func="$COVERAGE_OUT" | tail -1 | grep -Eo '[0-9]+\.[0-9]')"
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ inputs.coverage-dir }}
