name: Check

on:
  workflow_call:
    inputs:
      fetch-url:
        type: string
        default: ${{ github.repositoryUrl }}
      fetch-sha:
        type: string
        default: ${{ github.sha }}
    outputs:
      coverage_total:
        value: ${{ jobs.check.outputs.coverage_total }}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      coverage_total: ${{ steps.coverage.outputs.total }}
    steps:
      - name: Fetch and checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.fetch-url }}
          ref: ${{ inputs.fetch-sha }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Coverage
        id: coverage
        if: ${{ github.event_name }} == pull_request
        shell: bash
        env:
          COVERAGE_OUT: ./coverage.out
        run: |
          go test -coverprofile="$COVERAGE_OUT" ./...

          TOTAL="$(go tool cover -func="$COVERAGE_OUT" | tail -1 | grep -Eo '[0-9]+\.[0-9]')"
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"
