name: Pull Request

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  # Build and execute the PR's code to run tests and generate a coverage report.
  # Must run without any write access since we execute untrusted code (from the PR creator).
  check:
    name: Build, Lint and Test
    permissions: # drop permissions to execute PR code
      contents: read
    uses: ./.github/workflows/check.yml
    with:
      repository: ${{ github.event.pull_request.head.repo.name }}
      ref: ${{ github.event.pull_request.head.ref }}

  # Use the generated coverage to update the PR.
  # Store the coverage in the Wiki as that allows linking the HTML directly,
  # whereas artifacts are only available via a zip.
  publish-coverage:
    name: Publish Coverage
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Fetch and checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage.lcov.info
          minimum-coverage: 75
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
