name: Pull Request

on:
  push:
jobs:
  # Build and execute the PR's code to run tests and generate a coverage report.
  # Must run without any write access since we execute third-party code.
  check:
    name: Build, Lint and Test
    permissions: # drop permissions to execute PR code
      contents: read
    uses: ./.github/workflows/check.yml
    with:
      fetch-url: ${{ github.event.pull_request.head.repo.clone_url }}
      fetch-sha: ${{ github.event.pull_request.head.sha }}

  # Use the generated coverage to update the PR.
  # Store the coverage in the Wiki as that allows linking the HTML directly,
  # whereas artifacts are only available via a zip.
  publish-coverage:
    name: Publish Coverage
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Save Coverage to Wiki
        shell: bash
        run: |
          ls -lA ${{ needs.check.outputs.coverage-html }}
          ls -lA ${{ needs.check.outputs.coverage-out }}
