name: Pull Request

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  # Build and execute the PR's code to run tests and generate a coverage report.
  # Must run without any write access since we execute untrusted code (from the PR creator).
  check:
    name: Check
    permissions: # drop permissions to execute PR code
      contents: read
    uses: ./.github/workflows/check.yml
    with:
      repository: ${{ github.event.pull_request.head.repo.name }}
      ref: ${{ github.event.pull_request.head.ref }}

  # Use the generated coverage to update the PR.
  # Store the coverage in the Wiki as that allows linking the HTML directly,
  # whereas artifacts are only available via a zip.
  publish-coverage:
    name: Publish Coverage
    runs-on: ubuntu-latest
    needs: check
    if: always() # job failure might not be due to tests (there doesn't seem to be a more precise way to check)
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.check.outputs.coverage-artifact }}

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Fetch and checkout # lcov needs the sources
        uses: actions/checkout@v3

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ${{ needs.check.outputs.coverage-lcov }}
          minimum-coverage: 75
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
